version: '3.8'

services:
  ragecoop-v:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4499:4499/udp"
    stdin_open: true
    tty: true
    volumes:
      - ./Settings.xml:/app/Settings.xml
